### ISSUE TITLE
start-measurement step fails

### ISSUE THREAD

**Issue by jreimone** [green-coding-berlin/eco-ci-energy-estimation#26]
In my private repo the following step fails:

```yml
name: Daily execution of tests
on:
  schedule:
    - cron: '0 04 * * MON-FRI'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Energy Estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@v2
        with:
          task: start-measurement
```

Here is an excerpt of the log I see from the run:
```bash
Requirement already satisfied: tqdm==4.65.0 in /tmp/eco-ci/venv/lib/python3.10/site-packages (from -r /tmp/eco-ci/spec-power-model/requirements.txt (line 25)) (4.65.0)
Requirement already satisfied: tzdata==2023.3 in /tmp/eco-ci/venv/lib/python3.10/site-packages (from -r /tmp/eco-ci/spec-power-model/requirements.txt (line 26)) (2023.3)
Requirement already satisfied: xgboost==1.7.5 in /tmp/eco-ci/venv/lib/python3.10/site-packages (from -r /tmp/eco-ci/spec-power-model/requirements.txt (line 27)) (1.7.5)
jq: error (at <stdin>:1): Cannot iterate over null (null)
Error: Process completed with exit code 5.
```

Unfortunately, I couldn't reproduce it in my public repo in [this PR](https://github.com/jreimone/public-reproduction/pull/2). I know it's hard, but maybe you have an idea what the issue can be?
