### ISSUE TITLE
Composite GHA error for Cache hit

### ISSUE THREAD

**Issue by jreimone** [green-coding-berlin/eco-ci-energy-estimation#3]
I tried your GHA and it fails when executing [this step](https://github.com/green-coding-berlin/eco-ci-energy-estimation/blob/main/action.yml#L72-L81). Here is what I see in the log:

```shell
Run if [[  == 'true' ]]; then
  if [[  == 'true' ]]; then
    echo "Cache hit succeeded! 😀"
  else
    echo "Cache hit failed! ❌"
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
/home/runner/work/_temp/1aa3fbf8-bd06-[44](https://github.com/Staffbase/testio-management/actions/runs/4617917933/jobs/8164729482#step:3:51)9c-933a-ff[50](https://github.com/Staffbase/testio-management/actions/runs/4617917933/jobs/8164729482#step:3:58)8558acf7.sh: line 1: conditional binary operator expected
Error: Process completed with exit code 2.
```
As you can see the output `${{ steps.cache-pip.outputs.cache-hit }}` is empty and wasn't populated by the [previous step](https://github.com/green-coding-berlin/eco-ci-energy-estimation/blob/main/action.yml#L59-L70). In the end my workflow fails in the initialization step with: 
```shell
jq: error (at <stdin>:4): Cannot iterate over null (null)
Error: Process completed with exit code 5.
```
This error is thrown in your step provided [here](https://github.com/green-coding-berlin/eco-ci-energy-estimation/blob/main/action.yml#L98).

All this happens in my very first step of initializing the measurement by:
```yaml
steps:
      - name: Initialize Energy Estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@main
        with:
          task: start-measurement
```

Can you help fixing it?
